### PR TITLE
🐞  add 4.12 ocp values 🐞

### PR DESCRIPTION
**Pull request by eformat**
add override values file for ocp 4.12 deployment

### CODE REVIEW

**Comment by ckavili** [comment]
I don't have a v4.11 to try at the moment but do you know if these elasticsearch and logging operator values go for v4.11 too? cause also with this file https://github.com/rht-labs/enablement-framework/blob/main/tooling/charts/tl500-course-content/values-v4.11.yaml we could have something like _values for 4.10+_ in both chart folders 🤔 💭 would be more tidier 😁  if not, not sure if there is a better way to keep different values files for different versions 🫣

**Comment by eformat** [comment]
hi @ckavili .. this was the base chart - i did login OK to DevSpaces using this config.

no, they need to be separate - or at least they were separated when the base and tooling charts were separated (they used to be combined a long time ago).

i have not tested the other values file yet, but will get to it.

**Comment by ckavili** [comment]
oh yeah yeah by combining I meant, combining v411 and v412 in the base chart folder if they can work with the same operator values 👯  so I thought we could have one `values.yaml` and one `values-410plus.yaml` in both base and tooling charts - just to not have lots of values file buuutt doesn't have to be 🫣

**Comment by eformat** [comment]
ah i see. i was just checking an up to date 4.11 cluster and it seems that YES, the stable operator channels are now in there as well.

so .. i will test this out some more (4.11 and 4.12) .. and we can certainly rename the files to be 4.11-4.12.yaml (or similar) !!

**Comment by eformat** [comment]
ok .. have combined v4.11, v4.12  into v4.11+ files now .. let me test in both cluster versions before merging

**Comment by eformat** [comment]
@ckavili - OK .. i have tested this out OK in v4.11 now .. so both v4.12 and v.4.11 work OK with the current v4.11+ file(s)
i ran the test suite and logged into a CRW as tests :clap:

**Comment by ckavili** [comment]
yay! thanks Mike🤸🏻‍♀️👏🏼

**Pull request merged**
