### PR TITLE
Added IPA Server integration

### PR DESCRIPTION
**Pull request by acidonper**
Hi,

I have developed a new chart "module" to include IPA Server deployment, Openshift oauth provider manually configuration and some documentation about the process.

I would like to spend more time in the following weeks but I think it is a good starting point to integrate LDAP server installation.

Cheers!

### CODE REVIEW

**Comment by tylerauerbeck** [comment]
Thanks for the PR @acidonper. I'll take a look at this shortly and get back to you with some comments.

**Comment by eformat** [comment]
hey @springdo .. did you get further with this ?

https://github.com/springdo/helm-charts/tree/master/charts/ipa/templates

**Comment by eformat** [comment]
see also rhpds - https://github.com/redhat-cop/agnosticd/pull/4656

**Comment by ckavili** [comment]
hey @acidonper thanks for this! we moved IPA chart to [redhat-cop/helm-charts](https://github.com/redhat-cop/helm-charts/tree/master/charts/ipa) so closing this one! 🙏

**Pull request closed without merging**
