### PR TITLE
🎷cosign version is updated🎷

### PR DESCRIPTION
**Pull request by ckavili**
Required for https://github.com/rht-labs/tech-exercise/pull/282

### CODE REVIEW

**Review by springdo — APPROVED** [review]
Lgtm 🍯🍯

**Comment by springdo** [comment]
@ckavili is there something in the testing that needs fixing or should we bypass this for now? I understand you're doing a course now so don't want to block you

**Comment by ckavili** [comment]
thanks @springdo 🐻  I am trying to understand why it is failing as well. Checks should work..the last check `syft --version` returns successfully when I check locally 🤷

**Comment by springdo** [comment]
Hmmmm weird, we can circle back to this later. Could be worth investigating some time next week when you're clear of the course 🍯🐝

**Pull request merged**
