### PR TITLE
🐟 Fix stackrox registry integration 🐟

### PR DESCRIPTION
**Pull request by eformat**
fixes https://github.com/rht-labs/tech-exercise/issues/145
was raised over there, fixed in here.

- adds a job to configure the a generic docker registry using the tl500 pipeline service account secret
- binds the cluster role system:image-puller to tl500:pipeline service account so stackrox can pull all images

### CODE REVIEW

**Comment by eformat** [comment]
just testing - WIP ...

**Comment by eformat** [comment]
- tested the job runs and creates integration OK
- tested pipeline image scan OK

Screenshot from 2022-02-17 14-01-32

**Comment by eformat** [comment]
@ckavili @jfilipcz  ping

**Comment by jfilipcz** [comment]
pong:) LGTM

**Pull request merged**
