### PR TITLE
🦠 ocp 4.11 deploy 🦠

### PR DESCRIPTION
**Pull request by eformat**
Deploy TL500 to OpenShift 4.11

I have added new values-v4.11.yaml files and config that has the extra config for DevSpaces 

so all you have to do for 4.11 is use those files (the default values.yaml is still read) when deploying the charts (README has also been updated to reflect this)

### CODE REVIEW

**Comment by eformat** [comment]
the only breaking change appears to be CRW -> devspaces Operator renaming

-- PodSecurity "restricted:v1.24"
-- https://connect.redhat.com/en/blog/important-openshift-changes-pod-security-standards

Changes to PSP brings up the following *would violate PodSecurity "restricted:v1.24* warnings

(1) ldap group sync

```bash
~/git/openshift-management ⎇ master#edf0e91$ helm upgrade cronjob-ldap-group-sync ...
Release "cronjob-ldap-group-sync" does not exist. Installing it now.
W0827 13:13:31.916574 1084014 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0827 13:13:32.276515 1084014 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0827 13:13:32.276552 1084014 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "cronjob-ldap-group-sync" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "cronjob-ldap-group-sync" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "cronjob-ldap-group-sync" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "cronjob-ldap-group-sync" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
NAME: cronjob-ldap-group-sync
LAST DEPLOYED: Sat Aug 27 13:13:31 2022
NAMESPACE: cluster-ops
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
(2) tl500-base chart

```bash
tl500-base ⎇ main#2c40a76 $ helm upgrade --install tl500-base . \
        --namespace tl500 --create-namespace --timeout=20m
Release "tl500-base" does not exist. Installing it now.
W0827 13:15:09.349655 1085985 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "job" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "job" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "job" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "job" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0827 13:15:17.326350 1085985 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "controller" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "controller" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "controller" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0827 13:15:17.343673 1085985 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "tl500-teamsters" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "tl500-teamsters" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tl500-teamsters" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tl500-teamsters" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0827 13:15:18.666634 1085985 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "crd-check" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "crd-check" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "crd-check" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "crd-check" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**Comment by eformat** [comment]
Teamsters regression Testing Looks Good

```bash
create-ateam create  -> success
create-ateam create Tests run: 9
create-ateam create Failed tests: 0
create-ateam create All tests passed.
```

**Comment by ckavili** [comment]
I ❤️ Teamster

**Comment by eformat** [comment]
Related: https://github.com/rht-labs/tech-exercise/pull/232

**Comment by eformat** [comment]
I have adjusted values-4.11.yaml to work with base values.yaml files as both are evaluated by helm when you want 4.11 deployment:

```
helm upgrade --install tl500-base -f values-v4.11.yaml . --namespace tl500 --create-namespace 
helm upgrade --install tl500-course-content -f values-v411.yaml . --namespace tl500 --create-namespace
```

**Comment by jfilipcz** [comment]
One small thing, what happened with `tooling/charts/tl500-base/templates/gitlab/deployments.yaml` ?

**Comment by eformat** [comment]
> One small thing, what happened with `tooling/charts/tl500-base/templates/gitlab/deployments.yaml` ?

LOLZ ! i deleted it ;) thanx .. yeah my mistake, reverted it. its the only file that fails when doing helm template cause of the ldap injection

**Review by jfilipcz — APPROVED** [review]
LGTM! :japanese_ogre: :japanese_ogre:

**Comment by eformat** [comment]
OK i am gonna merge this and convert RHPDS to 4.11 as the test bed ...

**Pull request merged**
