### PR TITLE
Move cert-utils operator out of tl500-base main chart

### PR DESCRIPTION
**Pull request by jfilipcz**
That PR is to move the cert-utils operator subs creation from chart itself to operatorhub subchart, to make it easy to switch off or on. By default, Cert-Utils will be installed.

More details: https://github.com/rht-labs/enablement-framework/issues/120

### CODE REVIEW

**Comment by eformat** [comment]
hey @jfilipcz .. some comments on the approach here ...

(1) not sure what the need for this is ? is something pre-installing the cert-utils operator, normally TL500 tooling is installed onto a freshly installed cluster - no software added. do you know why this is necessary in the first place ?

(2) this operatorhub helm chart - has basically exactly the same subscription/og _templated as this chart has ! i.e. why use it at all ? since it does not allow subscription enable/disable functionality (its only cause you have a list of one atm).

(3) maybe in light of (2) just adding an "enable" flag in here:

https://github.com/rht-labs/enablement-framework/blob/main/tooling/charts/tl500-base/templates/operators/subscription.yaml#L2

and to each operator we wish to install add an "enable: true" is a lot easier and more readable ?

```
{{- if $op.subscription.enable }}
```

(4) if you really want to use the operatorhub helm chart, then add the enable/disable functionality from (2) in there, remove the templates in  tooling/charts/tl500-base/templates/operators and make all the operators use the chart?

**Review by eformat — CHANGES_REQUESTED** [review]
see comments! cheers.

**Comment by jfilipcz** [comment]
Yeah, the thing is lists are pita to handle from Helm command line:) And that was the reason why I've moved that to operatorhub chart - it's a quick workaround until I get the operator list in the main chart moved to something easier handled in the command line. I know that you have a fresh cluster, but in our case we set a few other things in the provisioning, and cert-utils operator is one of them. The coflict was happening when versions were different and OLM was not able to resolve TL500 InstallPlan dependencies. Ad 3. I didn't want to do that because I would need to store the entire operator list somewhere and the whole point was to avoid another configuration piece.

**Comment by eformat** [comment]
> 3. I didn't want to do that because I would need to store the entire operator list somewhere and the whole point was to avoid another configuration piece.

but we already have the operator list in values.yaml ? why not just keep this subscription "enable" thing local, dont include another dependency. job done ?

**Comment by jfilipcz** [comment]
I can easily switch on and off the entire subchart, but for the specific operator on the list, I would need to pass all of the parameters for specific operator (it's not possible to override only var on the list index, you need to specify all vars for specific list index). Let's assume we got one index list:

  - name: cluster-logging-operator
    namespace: openshift-logging
    enabled: true
    subscription:
      channel: stable-5.3
      approval: Automatic
      operatorName: cluster-logging
      source: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorgroup:
      create: true
 
in order to override that from command line, I would need to pass all vars, not only 'enabled'.

**Comment by jfilipcz** [comment]
I was thinking about dropping the list of operators, and use an ordinary structure instead, and that would solve the issue of accessing specific variable. 

so instead of
```   - name: cluster-logging-operator
    namespace: openshift-logging
    subscription:
      channel: stable-5.3
      approval: Automatic
      operatorName: cluster-logging
      source: redhat-operators
```
have something like that: ```
operators:
   cluster-logging-operator:
      namespace: openshift-logging
      subscription:
        channel: stable-5.3
        approval: Automatic
        operatorName: cluster-logging
        source: redhat-operators
``` but I didn't have time to look into that yet

**Comment by eformat** [comment]
Yeah. we ultimately did this **exact** same switch in UJ as well for similar reasons.

However, in this case, since the chart is not published and we operate directly on the values.yaml file you can just do this:

```bash
yq e '(.operators[] | select(.name=="cert-utils-operator").enabled) = false' -i values.yaml
```

and the full diff i was trying ...

```
diff --git a/tooling/charts/tl500-base/templates/operators/operatorgroup.yaml b/tooling/charts/tl500-base/templates/operators/operatorgroup.yaml
index 16dfb3a..366b433 100644
--- a/tooling/charts/tl500-base/templates/operators/operatorgroup.yaml
+++ b/tooling/charts/tl500-base/templates/operators/operatorgroup.yaml
@@ -1,4 +1,5 @@
 {{- range $op := .Values.operators }}
+{{- if $op.enabled }}
 {{- if $op.operatorgroup.create }}
 {{- $og := $op.operatorgroup }}
 ---
@@ -12,3 +13,4 @@ spec:
   - {{ $op.namespace }}
 {{- end }}
 {{- end }}
+{{- end }}
diff --git a/tooling/charts/tl500-base/templates/operators/subscription.yaml b/tooling/charts/tl500-base/templates/operators/subscription.yaml
index 97b18ef..66d65cf 100644
--- a/tooling/charts/tl500-base/templates/operators/subscription.yaml
+++ b/tooling/charts/tl500-base/templates/operators/subscription.yaml
@@ -1,5 +1,6 @@
 {{- range $op := .Values.operators }}
 {{- $sub := $op.subscription }}
+{{- if $op.enabled }}
 ---
 apiVersion: operators.coreos.com/v1alpha1
 kind: Subscription
@@ -16,4 +17,5 @@ spec:
   startingCSV: {{ $sub.csv }}
 {{- end }}
 {{- end }}
+{{- end }}
 
diff --git a/tooling/charts/tl500-base/values.yaml b/tooling/charts/tl500-base/values.yaml
index 578bda0..632806e 100644
--- a/tooling/charts/tl500-base/values.yaml
+++ b/tooling/charts/tl500-base/values.yaml
@@ -15,6 +15,7 @@ namespaces:
 
 operators:
   - name: codeready-workspaces
+    enabled: true
     namespace: tl500-workspaces
     subscription:
       channel: latest
@@ -27,6 +28,7 @@ operators:
 
   - name: openshift-pipelines-operator-rh
     namespace: openshift-operators
+    enabled: true
     subscription:
       channel: latest
       approval: Automatic
@@ -38,6 +40,7 @@ operators:
 
   - name: cert-utils-operator
     namespace: openshift-operators
+    enabled: true
     subscription:
       channel: alpha
       approval: Automatic
@@ -49,6 +52,7 @@ operators:
 
   - name: elasticsearch-operator
     namespace: openshift-operators
+    enabled: true
     subscription:
       channel: stable-5.3
       approval: Automatic
@@ -60,6 +64,7 @@ operators:
 
   - name: cluster-logging-operator
     namespace: openshift-logging
+    enabled: true
     subscription:
       channel: stable-5.3
       approval: Automatic
```

**Comment by jfilipcz** [comment]
On a development setup, sure - but for engagement environments we rely on published charts

**Comment by jfilipcz** [comment]
Hey @eformat, have a look at the way the things are done with the latest push - I've replaced operators list with dictionary, added `enabled` flag to operators etc.
I can finally do `--set operators.codeready-workspaces.enabled=false` :dancers:

**Review by eformat — APPROVED** [review]

**Pull request merged**
