### PR TITLE
🐳 donal - oh-my-zsh prompt_cr fixes 🐳

### PR DESCRIPTION
**Pull request by eformat**
fix for % showing up - see https://github.com/vercel/hyper/issues/2144 for more details

Screenshot from 2021-08-06 13-26-14

### CODE REVIEW

**Review by tylerauerbeck — APPROVED** [review]
LGTM

**Comment by tylerauerbeck** [comment]
@eformat LGTM. Anything else before we merge?

**Comment by eformat** [comment]
@tylerauerbeck  .. you KNOW how much i love zsh ;) not... picking these up as we test out the tech-exercise repo ... this is it for now .. i totally blame @springdo for this BTW

**Comment by eformat** [comment]
of @tylerauerbeck  pps: do this one first please ?

https://github.com/rht-labs/enablement-framework/pull/42

else image versioning and devfile gets a little messy ..

**Review by tylerauerbeck — APPROVED** [review]

**Comment by eformat** [comment]
this was approved .. merging

**Pull request merged**
