### PR TITLE
🐝 simplify chart install, remove race condition for install on empty cluster🐝

### PR DESCRIPTION
**Pull request by eformat**
supercedes #17 and #13

### CODE REVIEW

**Comment by eformat** [comment]
simplified chart, single chart, hooks for crw/crds.

**Comment by paulbarfuss** [comment]
Good stuff @eformat 

I used these bits to set up my cluster for an upcoming do500 and it was very smooth!

Please bump the version we'll get you merged in.

**Comment by eformat** [comment]
@paulbarfuss .. no worries, bumped chart.

i also disabled gitlab sign up .. users are  in ldap/SSO normally for this.

**Review by paulbarfuss — APPROVED** [review]
lgtm

**Pull request merged**
